"""Remove accounts generated by the project's automated tests from the local SQLite database."""

import sqlite3
import sys
import re
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from app.core.config import settings


TEST_USERNAME_PATTERN = re.compile(r"^test\d{3,}$")


def placeholders(values: list[int]) -> str:
    return ",".join("?" for _ in values)


def ids_for(connection: sqlite3.Connection, statement: str, values: list[int]) -> list[int]:
    if not values:
        return []
    return [row[0] for row in connection.execute(statement.format(ids=placeholders(values)), values)]


def delete_for(connection: sqlite3.Connection, table: str, column: str, values: list[int]) -> int:
    if not values:
        return 0
    return connection.execute(f"DELETE FROM {table} WHERE {column} IN ({placeholders(values)})", values).rowcount


def delete_for_user_or_itinerary(connection: sqlite3.Connection, user_ids: list[int], itinerary_ids: list[int]) -> int:
    clauses: list[str] = []
    values: list[int] = []
    if user_ids:
        clauses.append(f"user_id IN ({placeholders(user_ids)})")
        values.extend(user_ids)
    if itinerary_ids:
        clauses.append(f"itinerary_id IN ({placeholders(itinerary_ids)})")
        values.extend(itinerary_ids)
    if not clauses:
        return 0
    return connection.execute(f"DELETE FROM itinerary_feedback WHERE {' OR '.join(clauses)}", values).rowcount


def database_path() -> Path:
    prefix = "sqlite:///"
    if not settings.database_url.startswith(prefix):
        raise RuntimeError("此清理脚本只支持 SQLite 数据库")
    path = Path(settings.database_url.removeprefix(prefix))
    return path if path.is_absolute() else (Path.cwd() / path).resolve()


def main() -> None:
    apply = "--apply" in sys.argv[1:]
    path = database_path()
    connection = sqlite3.connect(path)
    connection.execute("PRAGMA foreign_keys = ON")
    test_users = [row for row in connection.execute("SELECT id, username FROM users") if TEST_USERNAME_PATTERN.fullmatch(row[1])]
    user_ids = [row[0] for row in test_users]
    session_ids = ids_for(connection, "SELECT id FROM chat_sessions WHERE user_id IN ({ids})", user_ids)
    itinerary_ids = ids_for(connection, "SELECT id FROM itineraries WHERE user_id IN ({ids})", user_ids)
    itinerary_ids = sorted(set(itinerary_ids + ids_for(connection, "SELECT id FROM itineraries WHERE session_id IN ({ids})", session_ids)))
    job_ids = ids_for(connection, "SELECT id FROM planning_jobs WHERE session_id IN ({ids})", session_ids)
    run_ids = sorted(set(ids_for(connection, "SELECT id FROM agent_runs WHERE job_id IN ({ids})", job_ids) + ids_for(connection, "SELECT id FROM agent_runs WHERE itinerary_id IN ({ids})", itinerary_ids)))
    day_ids = ids_for(connection, "SELECT id FROM itinerary_days WHERE itinerary_id IN ({ids})", itinerary_ids)

    print(f"database={path}")
    print("usernames=" + ", ".join(row[1] for row in test_users))
    print(f"test_users={len(user_ids)} sessions={len(session_ids)} itineraries={len(itinerary_ids)} jobs={len(job_ids)} agent_runs={len(run_ids)}")
    if not apply:
        print("dry_run=true; run with --apply to delete the listed test data")
        return

    deleted = {
        "agent_tool_calls": delete_for(connection, "agent_tool_calls", "agent_run_id", run_ids),
        "agent_runs": delete_for(connection, "agent_runs", "id", run_ids),
        "agent_events": delete_for(connection, "agent_events", "session_id", session_ids),
        "idempotency_records": delete_for(connection, "idempotency_records", "session_id", session_ids),
        "chat_messages": delete_for(connection, "chat_messages", "session_id", session_ids),
        "planning_jobs": delete_for(connection, "planning_jobs", "id", job_ids),
        "share_links": delete_for(connection, "share_links", "itinerary_id", itinerary_ids),
        "itinerary_feedback": delete_for_user_or_itinerary(connection, user_ids, itinerary_ids),
        "itinerary_validations": delete_for(connection, "itinerary_validations", "itinerary_id", itinerary_ids),
        "itinerary_revisions": delete_for(connection, "itinerary_revisions", "itinerary_id", itinerary_ids),
        "itinerary_stops": delete_for(connection, "itinerary_stops", "day_id", day_ids),
        "itinerary_days": delete_for(connection, "itinerary_days", "id", day_ids),
        "itineraries": delete_for(connection, "itineraries", "id", itinerary_ids),
        "favorites": delete_for(connection, "favorites", "user_id", user_ids),
        "recent_views": delete_for(connection, "recent_views", "user_id", user_ids),
        "user_profiles": delete_for(connection, "user_profiles", "user_id", user_ids),
        "auth_sessions": delete_for(connection, "auth_sessions", "user_id", user_ids),
        "chat_sessions": delete_for(connection, "chat_sessions", "id", session_ids),
        "users": delete_for(connection, "users", "id", user_ids),
    }
    connection.commit()
    print("deleted=" + ", ".join(f"{name}:{count}" for name, count in deleted.items() if count))


if __name__ == "__main__":
    main()
