"""align legacy schema

Revision ID: cba56ab58804
Revises: f20046effbac
Create Date: 2026-09-03 20:44:06.111494
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite


# revision identifiers, used by Alembic.
revision: str = 'cba56ab58804'
down_revision: Union[str, None] = 'f20046effbac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE itineraries SET preferences = '[]' WHERE preferences IS NULL")
    op.execute("UPDATE user_profiles SET avoid_places = '[]' WHERE avoid_places IS NULL")

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_sessions_archived_at'), ['archived_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_deleted_at'), ['deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_sessions_is_pinned'), ['is_pinned'], unique=False)

    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.alter_column('preferences',
               existing_type=sqlite.JSON(),
               nullable=False)

    with op.batch_alter_table('itinerary_feedback', schema=None) as batch_op:
        batch_op.create_foreign_key(
            'fk_itinerary_feedback_assigned_admin_id_users',
            'users',
            ['assigned_admin_id'],
            ['id'],
        )

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('avoid_places',
               existing_type=sqlite.JSON(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_deleted_at'), ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_deleted_at'))

    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.alter_column('avoid_places',
               existing_type=sqlite.JSON(),
               nullable=True)

    with op.batch_alter_table('itinerary_feedback', schema=None) as batch_op:
        batch_op.drop_constraint('fk_itinerary_feedback_assigned_admin_id_users', type_='foreignkey')

    with op.batch_alter_table('itineraries', schema=None) as batch_op:
        batch_op.alter_column('preferences',
               existing_type=sqlite.JSON(),
               nullable=True)

    with op.batch_alter_table('chat_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_sessions_is_pinned'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_deleted_at'))
        batch_op.drop_index(batch_op.f('ix_chat_sessions_archived_at'))

    # ### end Alembic commands ###
