"""initial schema

Revision ID: f20046effbac
Revises:
Create Date: 2026-09-03 20:39:37.853041
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'f20046effbac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_rate_limit_buckets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_hash', sa.String(length=64), nullable=False),
    sa.Column('window_started_at', sa.DateTime(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('blocked_until', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action', 'scope_type', 'scope_hash')
    )
    op.create_index(op.f('ix_auth_rate_limit_buckets_action'), 'auth_rate_limit_buckets', ['action'], unique=False)
    op.create_index(op.f('ix_auth_rate_limit_buckets_blocked_until'), 'auth_rate_limit_buckets', ['blocked_until'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('aliases', sa.JSON(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('season', sa.String(length=120), nullable=False),
    sa.Column('budget', sa.String(length=80), nullable=False),
    sa.Column('recommended_days', sa.String(length=40), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('support_level', sa.String(length=20), nullable=False),
    sa.Column('planning_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_is_active'), 'cities', ['is_active'], unique=False)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.create_index(op.f('ix_cities_slug'), 'cities', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=4), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_email_verified_at'), 'users', ['email_verified_at'], unique=False)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('actor_username', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('target_type', sa.String(length=40), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('summary', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_logs_action'), 'admin_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_actor_user_id'), 'admin_audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_created_at'), 'admin_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_target_id'), 'admin_audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_target_type'), 'admin_audit_logs', ['target_type'], unique=False)
    op.create_table('attractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('opening_hours', sa.String(length=120), nullable=False),
    sa.Column('ticket_price', sa.Integer(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('area', sa.String(length=80), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attractions_city_id'), 'attractions', ['city_id'], unique=False)
    op.create_index(op.f('ix_attractions_is_active'), 'attractions', ['is_active'], unique=False)
    op.create_index(op.f('ix_attractions_name'), 'attractions', ['name'], unique=False)
    op.create_table('auth_action_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('target_email', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_action_tokens_expires_at'), 'auth_action_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_auth_action_tokens_purpose'), 'auth_action_tokens', ['purpose'], unique=False)
    op.create_index(op.f('ix_auth_action_tokens_target_email'), 'auth_action_tokens', ['target_email'], unique=False)
    op.create_index(op.f('ix_auth_action_tokens_token_hash'), 'auth_action_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_auth_action_tokens_used_at'), 'auth_action_tokens', ['used_at'], unique=False)
    op.create_index(op.f('ix_auth_action_tokens_user_id'), 'auth_action_tokens', ['user_id'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_family_id', sa.String(length=36), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token_hash', sa.String(length=64), nullable=False),
    sa.Column('device_name', sa.String(length=200), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_sessions_refresh_token_hash'), 'auth_sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_auth_sessions_token_family_id'), 'auth_sessions', ['token_family_id'], unique=False)
    op.create_index(op.f('ix_auth_sessions_user_id'), 'auth_sessions', ['user_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('content_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_reports_reporter_id'), 'content_reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_content_reports_status'), 'content_reports', ['status'], unique=False)
    op.create_index(op.f('ix_content_reports_target_id'), 'content_reports', ['target_id'], unique=False)
    op.create_index(op.f('ix_content_reports_target_type'), 'content_reports', ['target_type'], unique=False)
    op.create_table('email_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('recipient_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('recipient_masked', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=180), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'sent', 'failed', 'simulated')"),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_outbox_created_at'), 'email_outbox', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_outbox_purpose'), 'email_outbox', ['purpose'], unique=False)
    op.create_index(op.f('ix_email_outbox_recipient_fingerprint'), 'email_outbox', ['recipient_fingerprint'], unique=False)
    op.create_index(op.f('ix_email_outbox_sent_at'), 'email_outbox', ['sent_at'], unique=False)
    op.create_index(op.f('ix_email_outbox_status'), 'email_outbox', ['status'], unique=False)
    op.create_index(op.f('ix_email_outbox_user_id'), 'email_outbox', ['user_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id')
    )
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('intercity_route_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_city_id', sa.Integer(), nullable=False),
    sa.Column('destination_city_id', sa.Integer(), nullable=False),
    sa.Column('transport', sa.String(length=30), nullable=False),
    sa.Column('service_date', sa.String(length=10), nullable=False),
    sa.Column('route_data', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destination_city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['origin_city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin_city_id', 'destination_city_id', 'transport', 'service_date')
    )
    op.create_index(op.f('ix_intercity_route_cache_destination_city_id'), 'intercity_route_cache', ['destination_city_id'], unique=False)
    op.create_index(op.f('ix_intercity_route_cache_expires_at'), 'intercity_route_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_intercity_route_cache_origin_city_id'), 'intercity_route_cache', ['origin_city_id'], unique=False)
    op.create_table('knowledge_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('source_name', sa.String(length=160), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('license_note', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_documents_city_id'), 'knowledge_documents', ['city_id'], unique=False)
    op.create_index(op.f('ix_knowledge_documents_status'), 'knowledge_documents', ['status'], unique=False)
    op.create_table('recent_views',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=20), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'target_type', 'target_id')
    )
    op.create_index(op.f('ix_recent_views_user_id'), 'recent_views', ['user_id'], unique=False)
    op.create_index(op.f('ix_recent_views_viewed_at'), 'recent_views', ['viewed_at'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=False),
    sa.Column('avoid_places', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('agent_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'event_id')
    )
    op.create_index(op.f('ix_agent_events_session_id'), 'agent_events', ['session_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.create_table('idempotency_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('response_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'session_id', 'action', 'key')
    )
    op.create_index(op.f('ix_idempotency_records_session_id'), 'idempotency_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_idempotency_records_user_id'), 'idempotency_records', ['user_id'], unique=False)
    op.create_table('itineraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('city_name', sa.String(length=80), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('budget_total', sa.Integer(), nullable=False),
    sa.Column('budget_scope', sa.String(length=120), nullable=False),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itineraries_deleted_at'), 'itineraries', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_itineraries_user_id'), 'itineraries', ['user_id'], unique=False)
    op.create_table('knowledge_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('embedding_model', sa.String(length=80), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['knowledge_documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'chunk_index')
    )
    op.create_index(op.f('ix_knowledge_chunks_document_id'), 'knowledge_chunks', ['document_id'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('attraction_id', sa.Integer(), nullable=True),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('content_key', sa.String(length=180), nullable=False),
    sa.Column('storage_type', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=80), nullable=True),
    sa.Column('alt_text', sa.String(length=240), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=True),
    sa.Column('source_author', sa.String(length=200), nullable=True),
    sa.Column('license_name', sa.String(length=120), nullable=True),
    sa.Column('attribution_url', sa.String(length=1000), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("storage_type IN ('remote_url', 'local_file', 'object_storage')"),
    sa.ForeignKeyConstraint(['attraction_id'], ['attractions.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'attraction_id', 'purpose')
    )
    op.create_index(op.f('ix_media_assets_attraction_id'), 'media_assets', ['attraction_id'], unique=False)
    op.create_index(op.f('ix_media_assets_city_id'), 'media_assets', ['city_id'], unique=False)
    op.create_index(op.f('ix_media_assets_content_key'), 'media_assets', ['content_key'], unique=False)
    op.create_index(op.f('ix_media_assets_is_active'), 'media_assets', ['is_active'], unique=False)
    op.create_index(op.f('ix_media_assets_verification_status'), 'media_assets', ['verification_status'], unique=False)
    op.create_table('planning_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('result_itinerary_id', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planning_jobs_session_id'), 'planning_jobs', ['session_id'], unique=False)
    op.create_index(op.f('ix_planning_jobs_status'), 'planning_jobs', ['status'], unique=False)
    op.create_table('ranking_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ranking_type', sa.String(length=20), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.Column('attraction_id', sa.Integer(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['attraction_id'], ['attractions.id'], ),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ranking_type', 'city_id', 'attraction_id', name='uq_ranking_entry_target')
    )
    op.create_index(op.f('ix_ranking_entries_attraction_id'), 'ranking_entries', ['attraction_id'], unique=False)
    op.create_index(op.f('ix_ranking_entries_city_id'), 'ranking_entries', ['city_id'], unique=False)
    op.create_index(op.f('ix_ranking_entries_is_active'), 'ranking_entries', ['is_active'], unique=False)
    op.create_index(op.f('ix_ranking_entries_ranking_type'), 'ranking_entries', ['ranking_type'], unique=False)
    op.create_table('retrieval_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(length=1000), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retrieval_runs_city_id'), 'retrieval_runs', ['city_id'], unique=False)
    op.create_index(op.f('ix_retrieval_runs_session_id'), 'retrieval_runs', ['session_id'], unique=False)
    op.create_table('route_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin_attraction_id', sa.Integer(), nullable=False),
    sa.Column('destination_attraction_id', sa.Integer(), nullable=False),
    sa.Column('transport', sa.String(length=30), nullable=False),
    sa.Column('service_date', sa.String(length=10), nullable=False),
    sa.Column('route_data', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['destination_attraction_id'], ['attractions.id'], ),
    sa.ForeignKeyConstraint(['origin_attraction_id'], ['attractions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origin_attraction_id', 'destination_attraction_id', 'transport', 'service_date')
    )
    op.create_index(op.f('ix_route_cache_destination_attraction_id'), 'route_cache', ['destination_attraction_id'], unique=False)
    op.create_index(op.f('ix_route_cache_expires_at'), 'route_cache', ['expires_at'], unique=False)
    op.create_index(op.f('ix_route_cache_origin_attraction_id'), 'route_cache', ['origin_attraction_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('algorithm_version', sa.String(length=40), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['planning_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_itinerary_id'), 'agent_runs', ['itinerary_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_job_id'), 'agent_runs', ['job_id'], unique=True)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=True),
    sa.Column('itinerary_snapshot', sa.JSON(), nullable=False),
    sa.Column('city_name', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_posts_author_id'), 'community_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_community_posts_city_name'), 'community_posts', ['city_name'], unique=False)
    op.create_index(op.f('ix_community_posts_created_at'), 'community_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_posts_itinerary_id'), 'community_posts', ['itinerary_id'], unique=False)
    op.create_index(op.f('ix_community_posts_status'), 'community_posts', ['status'], unique=False)
    op.create_table('itinerary_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_days_itinerary_id'), 'itinerary_days', ['itinerary_id'], unique=False)
    op.create_table('itinerary_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_admin_id', sa.Integer(), nullable=True),
    sa.Column('admin_reply', sa.Text(), nullable=True),
    sa.Column('replied_at', sa.DateTime(), nullable=True),
    sa.Column('handled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itinerary_id', 'user_id')
    )
    op.create_index(op.f('ix_itinerary_feedback_assigned_admin_id'), 'itinerary_feedback', ['assigned_admin_id'], unique=False)
    op.create_index(op.f('ix_itinerary_feedback_itinerary_id'), 'itinerary_feedback', ['itinerary_id'], unique=False)
    op.create_index(op.f('ix_itinerary_feedback_status'), 'itinerary_feedback', ['status'], unique=False)
    op.create_index(op.f('ix_itinerary_feedback_user_id'), 'itinerary_feedback', ['user_id'], unique=False)
    op.create_table('itinerary_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('itinerary_id', 'version_no')
    )
    op.create_index(op.f('ix_itinerary_revisions_itinerary_id'), 'itinerary_revisions', ['itinerary_id'], unique=False)
    op.create_table('itinerary_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_validations_itinerary_id'), 'itinerary_validations', ['itinerary_id'], unique=True)
    op.create_table('retrieval_hits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('retrieval_run_id', sa.Integer(), nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['knowledge_chunks.id'], ),
    sa.ForeignKeyConstraint(['retrieval_run_id'], ['retrieval_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('retrieval_run_id', 'chunk_id')
    )
    op.create_index(op.f('ix_retrieval_hits_chunk_id'), 'retrieval_hits', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_retrieval_hits_retrieval_run_id'), 'retrieval_hits', ['retrieval_run_id'], unique=False)
    op.create_table('share_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('itinerary_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_id'], ['itineraries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_share_links_itinerary_id'), 'share_links', ['itinerary_id'], unique=False)
    op.create_index(op.f('ix_share_links_token_hash'), 'share_links', ['token_hash'], unique=True)
    op.create_table('agent_tool_calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_run_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=80), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=False),
    sa.Column('output_data', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_run_id', 'sequence')
    )
    op.create_index(op.f('ix_agent_tool_calls_agent_run_id'), 'agent_tool_calls', ['agent_run_id'], unique=False)
    op.create_table('community_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_comments_author_id'), 'community_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_community_comments_created_at'), 'community_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_community_comments_post_id'), 'community_comments', ['post_id'], unique=False)
    op.create_index(op.f('ix_community_comments_status'), 'community_comments', ['status'], unique=False)
    op.create_table('community_post_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id')
    )
    op.create_index(op.f('ix_community_post_favorites_post_id'), 'community_post_favorites', ['post_id'], unique=False)
    op.create_index(op.f('ix_community_post_favorites_user_id'), 'community_post_favorites', ['user_id'], unique=False)
    op.create_table('community_post_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('alt_text', sa.String(length=240), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'sort_order')
    )
    op.create_index(op.f('ix_community_post_images_post_id'), 'community_post_images', ['post_id'], unique=False)
    op.create_index(op.f('ix_community_post_images_status'), 'community_post_images', ['status'], unique=False)
    op.create_table('community_post_likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'post_id')
    )
    op.create_index(op.f('ix_community_post_likes_post_id'), 'community_post_likes', ['post_id'], unique=False)
    op.create_index(op.f('ix_community_post_likes_user_id'), 'community_post_likes', ['user_id'], unique=False)
    op.create_table('itinerary_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('attraction_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['attraction_id'], ['attractions.id'], ),
    sa.ForeignKeyConstraint(['day_id'], ['itinerary_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_itinerary_stops_day_id'), 'itinerary_stops', ['day_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_itinerary_stops_day_id'), table_name='itinerary_stops')
    op.drop_table('itinerary_stops')
    op.drop_index(op.f('ix_community_post_likes_user_id'), table_name='community_post_likes')
    op.drop_index(op.f('ix_community_post_likes_post_id'), table_name='community_post_likes')
    op.drop_table('community_post_likes')
    op.drop_index(op.f('ix_community_post_images_status'), table_name='community_post_images')
    op.drop_index(op.f('ix_community_post_images_post_id'), table_name='community_post_images')
    op.drop_table('community_post_images')
    op.drop_index(op.f('ix_community_post_favorites_user_id'), table_name='community_post_favorites')
    op.drop_index(op.f('ix_community_post_favorites_post_id'), table_name='community_post_favorites')
    op.drop_table('community_post_favorites')
    op.drop_index(op.f('ix_community_comments_status'), table_name='community_comments')
    op.drop_index(op.f('ix_community_comments_post_id'), table_name='community_comments')
    op.drop_index(op.f('ix_community_comments_created_at'), table_name='community_comments')
    op.drop_index(op.f('ix_community_comments_author_id'), table_name='community_comments')
    op.drop_table('community_comments')
    op.drop_index(op.f('ix_agent_tool_calls_agent_run_id'), table_name='agent_tool_calls')
    op.drop_table('agent_tool_calls')
    op.drop_index(op.f('ix_share_links_token_hash'), table_name='share_links')
    op.drop_index(op.f('ix_share_links_itinerary_id'), table_name='share_links')
    op.drop_table('share_links')
    op.drop_index(op.f('ix_retrieval_hits_retrieval_run_id'), table_name='retrieval_hits')
    op.drop_index(op.f('ix_retrieval_hits_chunk_id'), table_name='retrieval_hits')
    op.drop_table('retrieval_hits')
    op.drop_index(op.f('ix_itinerary_validations_itinerary_id'), table_name='itinerary_validations')
    op.drop_table('itinerary_validations')
    op.drop_index(op.f('ix_itinerary_revisions_itinerary_id'), table_name='itinerary_revisions')
    op.drop_table('itinerary_revisions')
    op.drop_index(op.f('ix_itinerary_feedback_user_id'), table_name='itinerary_feedback')
    op.drop_index(op.f('ix_itinerary_feedback_status'), table_name='itinerary_feedback')
    op.drop_index(op.f('ix_itinerary_feedback_itinerary_id'), table_name='itinerary_feedback')
    op.drop_index(op.f('ix_itinerary_feedback_assigned_admin_id'), table_name='itinerary_feedback')
    op.drop_table('itinerary_feedback')
    op.drop_index(op.f('ix_itinerary_days_itinerary_id'), table_name='itinerary_days')
    op.drop_table('itinerary_days')
    op.drop_index(op.f('ix_community_posts_status'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_itinerary_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_created_at'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_city_name'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_author_id'), table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_job_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_itinerary_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_route_cache_origin_attraction_id'), table_name='route_cache')
    op.drop_index(op.f('ix_route_cache_expires_at'), table_name='route_cache')
    op.drop_index(op.f('ix_route_cache_destination_attraction_id'), table_name='route_cache')
    op.drop_table('route_cache')
    op.drop_index(op.f('ix_retrieval_runs_session_id'), table_name='retrieval_runs')
    op.drop_index(op.f('ix_retrieval_runs_city_id'), table_name='retrieval_runs')
    op.drop_table('retrieval_runs')
    op.drop_index(op.f('ix_ranking_entries_ranking_type'), table_name='ranking_entries')
    op.drop_index(op.f('ix_ranking_entries_is_active'), table_name='ranking_entries')
    op.drop_index(op.f('ix_ranking_entries_city_id'), table_name='ranking_entries')
    op.drop_index(op.f('ix_ranking_entries_attraction_id'), table_name='ranking_entries')
    op.drop_table('ranking_entries')
    op.drop_index(op.f('ix_planning_jobs_status'), table_name='planning_jobs')
    op.drop_index(op.f('ix_planning_jobs_session_id'), table_name='planning_jobs')
    op.drop_table('planning_jobs')
    op.drop_index(op.f('ix_media_assets_verification_status'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_is_active'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_content_key'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_city_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_attraction_id'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_knowledge_chunks_document_id'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_index(op.f('ix_itineraries_user_id'), table_name='itineraries')
    op.drop_index(op.f('ix_itineraries_deleted_at'), table_name='itineraries')
    op.drop_table('itineraries')
    op.drop_index(op.f('ix_idempotency_records_user_id'), table_name='idempotency_records')
    op.drop_index(op.f('ix_idempotency_records_session_id'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_agent_events_session_id'), table_name='agent_events')
    op.drop_table('agent_events')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_recent_views_viewed_at'), table_name='recent_views')
    op.drop_index(op.f('ix_recent_views_user_id'), table_name='recent_views')
    op.drop_table('recent_views')
    op.drop_index(op.f('ix_knowledge_documents_status'), table_name='knowledge_documents')
    op.drop_index(op.f('ix_knowledge_documents_city_id'), table_name='knowledge_documents')
    op.drop_table('knowledge_documents')
    op.drop_index(op.f('ix_intercity_route_cache_origin_city_id'), table_name='intercity_route_cache')
    op.drop_index(op.f('ix_intercity_route_cache_expires_at'), table_name='intercity_route_cache')
    op.drop_index(op.f('ix_intercity_route_cache_destination_city_id'), table_name='intercity_route_cache')
    op.drop_table('intercity_route_cache')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_email_outbox_user_id'), table_name='email_outbox')
    op.drop_index(op.f('ix_email_outbox_status'), table_name='email_outbox')
    op.drop_index(op.f('ix_email_outbox_sent_at'), table_name='email_outbox')
    op.drop_index(op.f('ix_email_outbox_recipient_fingerprint'), table_name='email_outbox')
    op.drop_index(op.f('ix_email_outbox_purpose'), table_name='email_outbox')
    op.drop_index(op.f('ix_email_outbox_created_at'), table_name='email_outbox')
    op.drop_table('email_outbox')
    op.drop_index(op.f('ix_content_reports_target_type'), table_name='content_reports')
    op.drop_index(op.f('ix_content_reports_target_id'), table_name='content_reports')
    op.drop_index(op.f('ix_content_reports_status'), table_name='content_reports')
    op.drop_index(op.f('ix_content_reports_reporter_id'), table_name='content_reports')
    op.drop_table('content_reports')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_auth_sessions_user_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_token_family_id'), table_name='auth_sessions')
    op.drop_index(op.f('ix_auth_sessions_refresh_token_hash'), table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index(op.f('ix_auth_action_tokens_user_id'), table_name='auth_action_tokens')
    op.drop_index(op.f('ix_auth_action_tokens_used_at'), table_name='auth_action_tokens')
    op.drop_index(op.f('ix_auth_action_tokens_token_hash'), table_name='auth_action_tokens')
    op.drop_index(op.f('ix_auth_action_tokens_target_email'), table_name='auth_action_tokens')
    op.drop_index(op.f('ix_auth_action_tokens_purpose'), table_name='auth_action_tokens')
    op.drop_index(op.f('ix_auth_action_tokens_expires_at'), table_name='auth_action_tokens')
    op.drop_table('auth_action_tokens')
    op.drop_index(op.f('ix_attractions_name'), table_name='attractions')
    op.drop_index(op.f('ix_attractions_is_active'), table_name='attractions')
    op.drop_index(op.f('ix_attractions_city_id'), table_name='attractions')
    op.drop_table('attractions')
    op.drop_index(op.f('ix_admin_audit_logs_target_type'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_target_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_created_at'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_actor_user_id'), table_name='admin_audit_logs')
    op.drop_index(op.f('ix_admin_audit_logs_action'), table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_email_verified_at'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_cities_slug'), table_name='cities')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_index(op.f('ix_cities_is_active'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_auth_rate_limit_buckets_blocked_until'), table_name='auth_rate_limit_buckets')
    op.drop_index(op.f('ix_auth_rate_limit_buckets_action'), table_name='auth_rate_limit_buckets')
    op.drop_table('auth_rate_limit_buckets')
    # ### end Alembic commands ###
