<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { Eye, EyeOff, Flag, ShieldAlert } from 'lucide-vue-next'
import { api, type CommunityPost } from '../api'

type Report = { id: number; target_type: string; target_id: number; reason: string; status: 'open' | 'resolved' | 'dismissed'; created_at: string; reporter: string }
const posts = ref<CommunityPost[]>([])
const reports = ref<Report[]>([])
const error = ref('')
const loading = ref(false)

async function load() { loading.value = true; try { const [postPage, reportItems] = await Promise.all([api<{ items: CommunityPost[] }>('/admin/community/posts?status=all'), api<Report[]>('/admin/community/reports?status=open')]); posts.value = postPage.items; reports.value = reportItems } catch (exception) { error.value = exception instanceof Error ? exception.message : '社区审核资料加载失败' } finally { loading.value = false } }
async function updatePost(post: CommunityPost, status: 'published' | 'hidden') { try { await api(`/admin/community/posts/${post.id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); await load() } catch (exception) { error.value = exception instanceof Error ? exception.message : '状态更新失败' } }
async function resolveReport(id: number, status: 'resolved' | 'dismissed') { try { await api(`/admin/community/reports/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); await load() } catch (exception) { error.value = exception instanceof Error ? exception.message : '举报处理失败' } }
onMounted(() => { void load() })
</script>

<template>
  <div class="page-container admin-community-page"><AdminModuleHeader eyebrow="COMMUNITY REVIEW" title="社区审核" description="查看公开行程、下架不合规内容并处理用户举报。" /><div v-if="error" class="empty-state"><ShieldAlert :size="28" /><h2>{{ error }}</h2></div><div v-else-if="loading" class="loading-state">正在加载社区内容...</div><template v-else><section class="admin-community-section"><div class="section-heading"><div><span class="eyebrow">OPEN REPORTS</span><h2>待处理举报</h2></div><Flag :size="20" class="accent-icon" /></div><div v-if="!reports.length" class="small-empty">暂无待处理举报</div><div v-else class="report-list"><article v-for="item in reports" :key="item.id"><div><strong>{{ item.target_type }} #{{ item.target_id }}</strong><span>{{ item.reporter }} · {{ new Date(item.created_at).toLocaleString() }}</span><p>{{ item.reason }}</p></div><div class="report-actions"><button class="secondary-button" @click="resolveReport(item.id, 'dismissed')">忽略</button><button class="primary-button" @click="resolveReport(item.id, 'resolved')">已处理</button></div></article></div></section><section class="admin-community-section"><div class="section-heading"><div><span class="eyebrow">POSTS</span><h2>行程帖子</h2></div></div><div v-if="!posts.length" class="small-empty">暂无社区帖子</div><div v-else class="post-review-list"><article v-for="post in posts" :key="post.id"><div class="post-review-main"><strong>{{ post.title }}</strong><span>{{ post.city_name }} · {{ post.author.name }} · {{ new Date(post.created_at).toLocaleString() }}</span><small>{{ post.like_count }} 次点赞 · {{ post.comment_count }} 条评论 · {{ post.images.length }} 张图片</small></div><span :class="['status-pill', post.status]">{{ post.status === 'published' ? '已公开' : '已下架' }}</span><button v-if="post.status === 'published'" class="icon-button" title="下架帖子" aria-label="下架帖子" @click="updatePost(post, 'hidden')"><EyeOff :size="18" /></button><button v-else class="icon-button" title="重新公开帖子" aria-label="重新公开帖子" @click="updatePost(post, 'published')"><Eye :size="18" /></button></article></div></section></template></div>
</template>

<style scoped>
.admin-community-page { max-width: 1120px; }.admin-community-section { margin-top: 42px; }.report-list, .post-review-list { border-top: 1px solid var(--color-border-soft); }.report-list article { display: flex; align-items: center; justify-content: space-between; gap: 24px; padding: 18px 0; border-bottom: 1px solid var(--color-border-soft); }.report-list strong, .post-review-main strong { display: block; color: var(--color-ink); font-size: 14px; }.report-list span, .post-review-main span, .post-review-main small { display: block; margin-top: 5px; color: var(--color-muted); font-size: 12px; }.report-list p { margin: 9px 0 0; color: var(--color-body); }.report-actions { display: flex; flex: none; gap: 8px; }.post-review-list article { display: grid; grid-template-columns: minmax(0, 1fr) auto 40px; gap: 12px; align-items: center; padding: 16px 0; border-bottom: 1px solid var(--color-border-soft); }.status-pill { padding: 5px 9px; border-radius: var(--radius-pill); background: var(--color-surface-soft); color: var(--color-muted); font-size: 12px; }.status-pill.published { color: var(--color-primary); }.post-review-list .icon-button { display: grid; width: 40px; height: 40px; place-items: center; border: 1px solid var(--color-border); border-radius: var(--radius-pill); color: var(--color-ink); }.post-review-list .icon-button:hover { border-color: var(--color-primary); color: var(--color-primary); }@media (max-width: 600px) { .report-list article { align-items: flex-start; flex-direction: column; }.report-actions { width: 100%; }.report-actions button { flex: 1; }.post-review-list article { grid-template-columns: minmax(0, 1fr) 40px; }.status-pill { justify-self: start; }.post-review-list .icon-button { grid-column: 2; grid-row: 1 / span 2; } }
</style>
