<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { CheckCircle2, ChevronLeft, ChevronRight, Clock3, Inbox, Send, Star, UserRound } from 'lucide-vue-next'
import { getAdminFeedback, getFeedbackAssignees, updateAdminFeedback, type AdminFeedback, type FeedbackAssignee } from '../api'
const items = ref<AdminFeedback[]>([]); const assignees = ref<FeedbackAssignee[]>([]); const error = ref(''); const page = ref(1); const pageSize = 10; const total = ref(0); const loading = ref(false); const savingId = ref<number | null>(null); const statusFilter = ref('all')
const pageCount = computed(() => Math.max(1, Math.ceil(total.value / pageSize)))
const pageNumbers = computed(() => { const start = Math.max(1, Math.min(page.value - 2, pageCount.value - 4)); const end = Math.min(pageCount.value, start + 4); return Array.from({ length: end - start + 1 }, (_, index) => start + index) })
function statusLabel(status: AdminFeedback['status']) { return ({ open: '待处理', in_progress: '处理中', resolved: '已解决' } as Record<string, string>)[status] }
async function loadFeedback(targetPage = page.value) { loading.value = true; try { const result = await getAdminFeedback(targetPage, statusFilter.value); const lastPage = Math.max(1, Math.ceil(result.total / pageSize)); if (targetPage > lastPage) return loadFeedback(lastPage); items.value = result.items; total.value = result.total; page.value = result.page } catch (exception) { error.value = exception instanceof Error ? exception.message : '反馈加载失败' } finally { loading.value = false } }
function goToPage(value: number) { if (value >= 1 && value <= pageCount.value && value !== page.value) void loadFeedback(value) }
async function saveFeedback(item: AdminFeedback) { savingId.value = item.id; error.value = ''; try { const updated = await updateAdminFeedback(item.id, { status: item.status, assigned_admin_id: item.assigned_admin_id, admin_reply: item.admin_reply }); items.value = items.value.map((candidate) => candidate.id === item.id ? updated : candidate) } catch (exception) { error.value = exception instanceof Error ? exception.message : '反馈处理保存失败'; await loadFeedback() } finally { savingId.value = null } }
onMounted(async () => { try { assignees.value = await getFeedbackAssignees() } catch (exception) { error.value = exception instanceof Error ? exception.message : '管理员列表加载失败' } await loadFeedback() })
</script>
<template><div class="page-container"><AdminModuleHeader eyebrow="FEEDBACK INBOX" title="反馈收件箱" description="分派、回复并跟踪用户对行程的反馈处理状态。" /><div class="toolbar"><label>状态<select v-model="statusFilter" @change="loadFeedback(1)"><option value="all">全部</option><option value="open">待处理</option><option value="in_progress">处理中</option><option value="resolved">已解决</option></select></label></div><div v-if="error" class="empty-state"><Inbox :size="28" /><h2>{{ error }}</h2></div><template v-else><div v-if="loading" class="empty-state"><p>正在加载反馈...</p></div><div v-else-if="!items.length" class="empty-state"><Inbox :size="28" /><h2>暂时没有符合条件的反馈</h2></div><div v-else class="feedback-list"><article v-for="item in items" :key="item.id" class="feedback-item"><div class="feedback-head"><strong>{{ item.username }}</strong><span>{{ item.email }}</span><time>{{ new Date(item.created_at).toLocaleString() }}</time></div><div class="feedback-meta"><span>{{ item.city_name }} · {{ item.itinerary_title }}</span><strong><Star :size="15" fill="currentColor" /> {{ item.rating }}/10</strong></div><p>{{ item.comment || '用户未留下文字评论' }}</p><div class="workflow"><label>状态<select v-model="item.status"><option value="open">待处理</option><option value="in_progress">处理中</option><option value="resolved">已解决</option></select></label><label><UserRound :size="14" />分派给<select v-model="item.assigned_admin_id"><option :value="null">未分派</option><option v-for="admin in assignees" :key="admin.id" :value="admin.id">{{ admin.username }}</option></select></label><span :class="['status', item.status]"><Clock3 v-if="item.status === 'open'" :size="14" /><CheckCircle2 v-else-if="item.status === 'resolved'" :size="14" /><Send v-else :size="14" />{{ statusLabel(item.status) }}</span></div><label class="reply-field">管理员回复<textarea v-model="item.admin_reply" rows="3" maxlength="2000" placeholder="向用户说明处理结果或下一步安排"></textarea></label><div class="workflow-footer"><small v-if="item.assigned_admin_username">当前负责人：{{ item.assigned_admin_username }}</small><button class="primary-button" :disabled="savingId === item.id" @click="saveFeedback(item)"><Send :size="16" />{{ savingId === item.id ? '保存中...' : '保存处理' }}</button></div></article></div><div v-if="total" class="admin-pagination"><span>共 {{ total }} 条反馈，第 {{ page }} / {{ pageCount }} 页</span><div><button class="admin-page-button" :disabled="page === 1 || loading" title="上一页" @click="goToPage(page - 1)"><ChevronLeft :size="16" /></button><button v-for="number in pageNumbers" :key="number" :class="['admin-page-button', { active: number === page }]" :disabled="loading" @click="goToPage(number)">{{ number }}</button><button class="admin-page-button" :disabled="page === pageCount || loading" title="下一页" @click="goToPage(page + 1)"><ChevronRight :size="16" /></button></div></div></template></div></template>
<style scoped>.toolbar{display:flex;justify-content:flex-end;margin-top:24px}.toolbar label,.workflow label,.reply-field{display:grid;gap:6px;color:var(--color-muted);font-size:12px}.toolbar select,.workflow select,.reply-field textarea{padding:9px;border:1px solid var(--color-border);border-radius:var(--radius-control);background:var(--color-surface);color:var(--color-ink)}.feedback-list{margin-top:18px;border-top:1px solid var(--border)}.feedback-item{padding:22px 0;border-bottom:1px solid var(--border)}.feedback-head,.feedback-meta{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.feedback-head span,.feedback-head time{color:var(--secondary);font-size:11px}.feedback-head time{margin-left:auto}.feedback-meta{justify-content:space-between;margin-top:12px;color:var(--primary);font-size:13px}.feedback-meta strong,.status{display:flex;align-items:center;gap:5px;color:var(--accent)}.feedback-item p{margin:12px 0}.workflow{display:flex;align-items:end;gap:12px;flex-wrap:wrap;margin-top:18px}.workflow label:nth-child(2){display:flex;align-items:center;gap:5px}.status{padding:8px 0;font-size:12px}.status.resolved{color:var(--color-primary)}.reply-field{margin-top:14px}.reply-field textarea{resize:vertical}.workflow-footer{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-top:12px}.workflow-footer small{color:var(--color-muted);font-size:12px}@media(max-width:600px){.feedback-head time{margin-left:0;width:100%}.toolbar{justify-content:flex-start}.workflow-footer{align-items:stretch;flex-direction:column}.workflow-footer button{width:100%}}</style>
