<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ArrowLeft, BookOpenText, Check, Plus, Save } from 'lucide-vue-next'
import { api, getCities, type City } from '../api'

type KnowledgeDocument = { id:number; city_id:number; city_name:string; title:string; source_name:string; source_url:string|null; license_note:string|null; content:string; status:'needs_review'|'approved'|'rejected'|'archived'; chunk_count:number; updated_at:string }
const cities = ref<City[]>([]); const items = ref<KnowledgeDocument[]>([]); const status = ref('all'); const error = ref(''); const notice = ref(''); const editingId = ref<number | null>(null)
const form = ref({ city_id: 0, title: '', source_name: '', source_url: '', license_note: '', content: '', status: 'needs_review' as KnowledgeDocument['status'] })
const statusLabel = computed(() => ({ all: '全部', needs_review: '待审核', approved: '已发布', rejected: '已拒绝', archived: '已归档' }))
function reset() { editingId.value = null; form.value = { city_id: cities.value[0]?.id || 0, title: '', source_name: '', source_url: '', license_note: '', content: '', status: 'needs_review' }; notice.value = '' }
function edit(item: KnowledgeDocument) { editingId.value = item.id; form.value = { city_id: item.city_id, title: item.title, source_name: item.source_name, source_url: item.source_url || '', license_note: item.license_note || '', content: item.content, status: item.status }; notice.value = '' }
async function load() { items.value = await api<KnowledgeDocument[]>(`/admin/knowledge-documents?status=${status.value}`) }
async function save() { try { if (!form.value.city_id || !form.value.title.trim() || !form.value.source_name.trim() || form.value.content.trim().length < 80) throw new Error('请填写城市、标题、来源和至少 80 字的攻略正文'); const body = { ...form.value, title: form.value.title.trim(), source_name: form.value.source_name.trim(), source_url: form.value.source_url.trim() || null, license_note: form.value.license_note.trim() || null, content: form.value.content.trim() }; await api(editingId.value ? `/admin/knowledge-documents/${editingId.value}` : '/admin/knowledge-documents', { method: editingId.value ? 'PATCH' : 'POST', body: JSON.stringify(body) }); await load(); notice.value = editingId.value ? '攻略资料已更新' : '攻略资料已录入，等待审核'; reset() } catch (exception) { error.value = exception instanceof Error ? exception.message : '保存失败' } }
async function changeStatus(item: KnowledgeDocument, next: KnowledgeDocument['status']) { edit(item); form.value.status = next; await save() }
onMounted(async () => { try { cities.value = await getCities(); await load(); reset() } catch (exception) { error.value = exception instanceof Error ? exception.message : '知识库加载失败' } })
</script>

<template><div class="page-container knowledge-page"><RouterLink class="back-link" to="/admin"><ArrowLeft :size="16" />返回管理后台</RouterLink><AdminModuleHeader eyebrow="GUIDE KNOWLEDGE" title="攻略知识库" description="录入有来源的城市攻略，审核通过后才能参与本地 RAG 检索。" /><div v-if="error" class="empty-state"><BookOpenText :size="28" /><h2>{{ error }}</h2></div><template v-else><div class="admin-toolbar"><div class="admin-toolbar-group"><button v-for="(_, key) in statusLabel" :key="key" :class="['admin-filter-button', { active: status === key }]" @click="status = key; load()">{{ statusLabel[key as keyof typeof statusLabel] }}</button></div><button class="secondary-button" @click="reset"><Plus :size="16" />新建资料</button></div><p v-if="notice" class="admin-notice">{{ notice }}</p><div class="knowledge-layout"><section class="knowledge-list"><article v-for="item in items" :key="item.id" :class="['knowledge-item', { selected: editingId === item.id }]" @click="edit(item)"><div><strong>{{ item.title }}</strong><span>{{ item.city_name }} · {{ item.source_name }}</span><small>切片 {{ item.chunk_count }} · {{ new Date(item.updated_at).toLocaleDateString() }}</small></div><span :class="['admin-status', item.status]">{{ statusLabel[item.status] }}</span></article><div v-if="!items.length" class="admin-page-empty"><p>暂无此状态的攻略资料</p></div></section><section class="admin-editor"><div class="admin-editor-heading"><h2>{{ editingId ? '编辑攻略资料' : '录入攻略资料' }}</h2><button v-if="editingId" class="admin-table-action" title="新建资料" @click="reset"><Plus :size="16" /></button></div><div class="admin-form-grid"><label>所属城市<select v-model.number="form.city_id"><option v-for="city in cities" :key="city.id" :value="city.id">{{ city.name }}</option></select></label><label>审核状态<select v-model="form.status"><option value="needs_review">待审核</option><option value="approved">审核通过</option><option value="rejected">拒绝</option><option value="archived">归档</option></select></label><label>标题<input v-model="form.title" maxlength="160" /></label><label>来源名称<input v-model="form.source_name" maxlength="160" /></label><label>来源链接<input v-model="form.source_url" type="url" placeholder="https://" /></label><label>许可说明<input v-model="form.license_note" maxlength="500" /></label></div><label class="content-label">攻略正文<textarea v-model="form.content" rows="14" maxlength="30000" placeholder="录入经确认可使用的城市文化、美食、漫游建议或注意事项。"></textarea><small>{{ form.content.length }} / 30000，至少 80 字</small></label><div class="editor-actions"><button class="primary-button" @click="save"><Save :size="16" />保存资料</button><button v-if="editingId && form.status !== 'approved'" class="secondary-button" @click="changeStatus(items.find(item => item.id === editingId)!, 'approved')"><Check :size="16" />审核通过</button></div></section></div></template></div></template>
<style scoped>.back-link{display:inline-flex;align-items:center;gap:6px;margin-bottom:22px;color:var(--color-primary);font-size:13px}.knowledge-layout{display:grid;grid-template-columns:minmax(280px,.8fr) minmax(0,1.2fr);gap:28px;margin-top:22px}.knowledge-list{border-top:1px solid var(--color-border-soft)}.knowledge-item{display:flex;justify-content:space-between;gap:10px;padding:15px 0;border-bottom:1px solid var(--color-border-soft);cursor:pointer}.knowledge-item:hover,.knowledge-item.selected{background:var(--color-surface-soft)}.knowledge-item strong,.knowledge-item span,.knowledge-item small{display:block}.knowledge-item strong{font-size:14px}.knowledge-item span,.knowledge-item small,.content-label small{margin-top:5px;color:var(--color-muted);font-size:12px}.admin-status.needs_review{color:var(--color-primary)}.admin-status.approved{color:var(--color-ink)}.admin-status.rejected,.admin-status.archived{color:var(--color-muted)}.content-label{display:grid;gap:7px;margin-top:14px;color:var(--color-muted);font-size:12px}.content-label textarea{width:100%;padding:12px;border:1px solid var(--color-border);border-radius:var(--radius-control);background:var(--color-surface);color:var(--color-ink);resize:vertical}.editor-actions{display:flex;gap:10px;margin-top:16px}@media(max-width:850px){.knowledge-layout{grid-template-columns:1fr}.knowledge-list{max-height:320px;overflow:auto}}</style>
