<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ChevronLeft, ChevronRight, Inbox, Star } from 'lucide-vue-next'
import { api } from '../api'
type Feedback = { id:number; itinerary_id:number; username:string; email:string; city_name:string; itinerary_title:string; rating:number; comment:string; created_at:string; updated_at:string }
const items = ref<Feedback[]>([]); const error = ref(''); const page = ref(1); const pageSize = 10; const total = ref(0); const loading = ref(false)
const pageCount = computed(() => Math.max(1, Math.ceil(total.value / pageSize)))
const pageNumbers = computed(() => { const start = Math.max(1, Math.min(page.value - 2, pageCount.value - 4)); const end = Math.min(pageCount.value, start + 4); return Array.from({ length: end - start + 1 }, (_, index) => start + index) })
async function loadFeedback(targetPage = page.value) { loading.value = true; try { const result = await api<{ items: Feedback[]; total: number; page: number; page_size: number }>(`/admin/feedback?page=${targetPage}&page_size=${pageSize}`); const lastPage = Math.max(1, Math.ceil(result.total / pageSize)); if (targetPage > lastPage) return loadFeedback(lastPage); items.value = result.items; total.value = result.total; page.value = result.page } catch (exception) { error.value = exception instanceof Error ? exception.message : '反馈加载失败' } finally { loading.value = false } }
function goToPage(value: number) { if (value >= 1 && value <= pageCount.value && value !== page.value) void loadFeedback(value) }
onMounted(() => { void loadFeedback() })
</script>
<template><div class="page-container"><AdminModuleHeader eyebrow="FEEDBACK INBOX" title="反馈收件箱" description="集中查看用户对已生成行程的评分和评论。" /><div v-if="error" class="empty-state"><Inbox :size="28" /><h2>{{ error }}</h2></div><template v-else><div v-if="loading" class="empty-state"><p>正在加载反馈...</p></div><div v-else-if="!items.length" class="empty-state"><Inbox :size="28" /><h2>暂时没有用户反馈</h2></div><div v-else class="feedback-list"><article v-for="item in items" :key="item.id" class="feedback-item"><div class="feedback-head"><strong>{{ item.username }}</strong><span>{{ item.email }}</span><time>{{ new Date(item.created_at).toLocaleString() }}</time></div><div class="feedback-meta"><span>{{ item.city_name }} · {{ item.itinerary_title }}</span><strong><Star :size="15" fill="currentColor" /> {{ item.rating }}/10</strong></div><p>{{ item.comment || '用户未留下文字评论' }}</p></article></div><div v-if="total" class="admin-pagination"><span>共 {{ total }} 条反馈，第 {{ page }} / {{ pageCount }} 页</span><div><button class="admin-page-button" :disabled="page === 1 || loading" title="上一页" @click="goToPage(page - 1)"><ChevronLeft :size="16" /></button><button v-for="number in pageNumbers" :key="number" :class="['admin-page-button', { active: number === page }]" :disabled="loading" @click="goToPage(number)">{{ number }}</button><button class="admin-page-button" :disabled="page === pageCount || loading" title="下一页" @click="goToPage(page + 1)"><ChevronRight :size="16" /></button></div></div></template></div></template>
<style scoped>.feedback-list{margin-top:34px;border-top:1px solid var(--border)}.feedback-item{padding:18px 0;border-bottom:1px solid var(--border)}.feedback-head,.feedback-meta{display:flex;align-items:center;gap:12px;flex-wrap:wrap}.feedback-head span,.feedback-head time{color:var(--secondary);font-size:11px}.feedback-head time{margin-left:auto}.feedback-meta{justify-content:space-between;margin-top:12px;color:var(--primary);font-size:13px}.feedback-meta strong{display:flex;align-items:center;gap:5px;color:var(--accent)}.feedback-item p{margin:12px 0 0}@media(max-width:600px){.feedback-head time{margin-left:0;width:100%}}</style>
