<script setup lang="ts">
import { onMounted, ref, watch } from 'vue'
import { ArrowLeft, TrendingUp } from 'lucide-vue-next'
import { getCities, getRankings, type City, type Ranking } from '../api'
const cities = ref<City[]>([]); const selectedCityId = ref(0); const rankings = ref<Ranking[]>([]); const loading = ref(true); const error = ref('')
async function load() { loading.value = true; try { rankings.value = await getRankings('attraction', selectedCityId.value || undefined) } catch (e) { error.value = e instanceof Error ? e.message : '排行加载失败' } finally { loading.value = false } }
watch(selectedCityId, load)
onMounted(async () => { cities.value = await getCities(); await load() })
</script>
<template><div class="page-container ranking-page"><RouterLink class="back-link" to="/"><ArrowLeft :size="16" />返回发现</RouterLink><div class="page-title-row"><div><span class="eyebrow">CURRENT DATA RANKING</span><h1>景点热度榜</h1><p>按资料完整度、标签匹配、可达性和游览时长计算初始热度。</p></div><TrendingUp :size="28" class="accent-icon" /></div><div class="ranking-filter"><button v-for="city in cities" :key="city.id" :class="['admin-filter-button', { active: selectedCityId === city.id }]" @click="selectedCityId = city.id">{{ city.name }}</button><button :class="['admin-filter-button', { active: selectedCityId === 0 }]" @click="selectedCityId = 0">全部城市</button></div><div v-if="loading" class="loading-state">正在计算排行...</div><div v-else-if="error" class="empty-state"><h2>{{ error }}</h2></div><div v-else class="ranking-list"><div v-for="item in rankings" :key="`${item.city_id}-${item.attraction_id}`" class="ranking-row"><span class="rank-number">{{ String(item.rank).padStart(2, '0') }}</span><strong>{{ item.name }}<small>{{ cities.find((city) => city.id === item.city_id)?.name }} · {{ item.data_source === 'initialization_heuristic' ? '初始化算法' : item.data_source }}</small></strong><span class="score">{{ item.score }}</span></div></div></div></template>
<style scoped>.ranking-page{max-width:800px}.back-link{display:inline-flex;align-items:center;gap:6px;color:var(--primary);font-size:13px;margin-bottom:26px}.accent-icon{color:var(--accent);margin-top:20px}.ranking-filter{display:flex;gap:8px;flex-wrap:wrap;margin:30px 0 16px}.admin-filter-button{border:1px solid var(--border);background:var(--surface);color:var(--secondary);padding:8px 12px;font-size:12px}.admin-filter-button.active{background:var(--primary-soft);border-color:var(--primary);color:var(--primary)}.ranking-list{border-top:1px solid var(--border)}.ranking-list .ranking-row{padding:17px 4px}.ranking-row strong{display:grid;gap:4px}.ranking-row small{font-size:11px;font-weight:400;color:var(--secondary)}</style>
