<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ArrowLeft, KeyRound, MailCheck, Monitor, ShieldCheck, UserRound } from 'lucide-vue-next'
import { useRouter } from 'vue-router'
import { changeEmail, changePassword, getAuthSessions, logoutAllDevices, revokeAuthSession } from '../api'
const router = useRouter(); const sessions = ref<{ id:number; device_name:string|null; created_at:string; last_used_at:string; expires_at:string; current:boolean }[]>([]); const password = ref(''); const newPassword = ref(''); const email = ref(''); const emailPassword = ref(''); const message = ref(''); const error = ref(''); const saving = ref(false); const devActionUrl = ref('')
async function load() { try { sessions.value = await getAuthSessions() } catch (e) { error.value = e instanceof Error ? e.message : '安全信息加载失败' } }
async function updatePassword() { message.value = ''; error.value = ''; devActionUrl.value = ''; if (newPassword.value.length < 10) { error.value = '新密码至少需要 10 个字符'; return } saving.value = true; try { await changePassword(password.value, newPassword.value); message.value = '密码已修改，所有设备已退出，请重新登录'; password.value = ''; newPassword.value = ''; window.dispatchEvent(new Event('auth-signed-out')); setTimeout(() => router.push('/'), 700) } catch (e) { error.value = e instanceof Error ? e.message : '密码修改失败' } finally { saving.value = false } }
async function updateEmail() { saving.value = true; message.value = ''; error.value = ''; devActionUrl.value = ''; try { const result = await changeEmail(emailPassword.value, email.value); message.value = result.message; devActionUrl.value = result.dev_action_url || ''; emailPassword.value = '' } catch (e) { error.value = e instanceof Error ? e.message : '邮箱修改失败' } finally { saving.value = false } }
async function logoutDevice(item: { id: number; current: boolean }) { if (item.current) return; try { await revokeAuthSession(item.id); sessions.value = sessions.value.filter((session) => session.id !== item.id); message.value = '已退出该设备'; error.value = '' } catch (e) { error.value = e instanceof Error ? e.message : '退出设备失败' } }
async function logoutAll() { await logoutAllDevices(); window.dispatchEvent(new Event('auth-signed-out')); await router.push('/') }
onMounted(load)
</script>
<template><div class="page-container security-page"><RouterLink class="back-link" to="/me"><ArrowLeft :size="16" />返回用户主页</RouterLink><div class="page-title-row"><div><span class="eyebrow">ACCOUNT SECURITY</span><h1>账号安全</h1><p>修改密码、邮箱并管理登录设备。</p></div><ShieldCheck :size="28" class="accent-icon" /></div><p v-if="message" class="success-banner">{{ message }}</p><p v-if="error" class="form-error">{{ error }}</p><a v-if="devActionUrl" class="dev-action-link" :href="devActionUrl"><MailCheck :size="16" />打开本地测试邮件链接</a><section class="security-section"><div class="section-heading"><div><span class="eyebrow">PASSWORD</span><h2>修改密码</h2></div><KeyRound :size="19" /></div><form @submit.prevent="updatePassword"><label>当前密码<input v-model="password" type="password" autocomplete="current-password" required /></label><label>新密码<input v-model="newPassword" type="password" autocomplete="new-password" minlength="10" placeholder="至少 10 个字符" required /></label><button class="primary-button" :disabled="saving">保存新密码</button></form></section><section class="security-section"><div class="section-heading"><div><span class="eyebrow">EMAIL</span><h2>修改邮箱</h2></div><UserRound :size="19" /></div><form @submit.prevent="updateEmail"><label>新邮箱<input v-model="email" type="email" autocomplete="email" required /></label><label>当前密码<input v-model="emailPassword" type="password" autocomplete="current-password" required /></label><button class="secondary-button" :disabled="saving">发送确认邮件</button></form><small class="muted-note">当前邮箱会一直保留，只有打开新邮箱中的确认链接后才会更换。</small></section><section class="security-section"><div class="section-heading"><div><span class="eyebrow">DEVICES</span><h2>登录设备</h2></div><Monitor :size="19" /></div><div v-for="item in sessions" :key="item.id" class="device-row"><span><Monitor :size="17" /><strong>{{ item.device_name || '未知设备' }}</strong></span><div class="device-actions"><small>{{ item.current ? '当前设备' : '已登录设备' }} · {{ new Date(item.last_used_at).toLocaleString() }}</small><button v-if="!item.current" type="button" @click="logoutDevice(item)">退出此设备</button></div></div><button class="danger-button-wide" :disabled="!sessions.length" @click="logoutAll">退出全部设备</button></section></div></template>
<style scoped>.security-page{max-width:900px}.back-link{display:inline-flex;align-items:center;gap:6px;color:var(--color-primary);font-size:14px;margin-bottom:26px}.accent-icon{color:var(--color-primary);margin-top:20px}.security-section{padding-top:32px;margin-top:32px;border-top:1px solid var(--color-border-soft)}.security-section form{max-width:480px;display:grid;gap:16px}.security-section label{display:grid;gap:7px;color:var(--color-muted);font-size:13px}.security-section input{min-height:48px;padding:12px;border:1px solid var(--color-border);border-radius:var(--radius-control);background:var(--color-surface);color:var(--color-ink);outline:0}.security-section input:focus{border-color:var(--color-ink)}.device-row{display:flex;justify-content:space-between;align-items:center;gap:16px;padding:16px 0;border-bottom:1px solid var(--color-border-soft)}.device-row span{display:flex;align-items:center;gap:8px;color:var(--color-ink)}.device-row small,.muted-note{color:var(--color-muted);font-size:13px}.device-actions{display:flex;align-items:center;gap:12px}.device-actions button{min-height:36px;padding:7px 12px;border:1px solid var(--color-border);border-radius:var(--radius-control);background:transparent;color:var(--color-danger);font-size:13px}.device-actions button:hover{border-color:var(--color-danger)}.danger-button-wide{min-height:48px;margin-top:20px;padding:0 16px;border:1px solid var(--color-danger);border-radius:var(--radius-control);background:transparent;color:var(--color-danger)}.success-banner{padding:12px;border-radius:var(--radius-control);background:var(--color-surface-soft);color:var(--color-ink);font-size:14px}.form-error{color:var(--color-danger);font-size:14px}.dev-action-link{display:inline-flex;align-items:center;gap:7px;margin-top:12px;color:var(--color-primary);font-size:13px;text-decoration:underline}@media(max-width:600px){.device-row{align-items:flex-start;flex-direction:column}.device-actions{width:100%;align-items:flex-start;flex-direction:column}.device-actions button{width:100%}}
</style>
