<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ArrowLeft, KeyRound, Monitor, ShieldCheck, UserRound } from 'lucide-vue-next'
import { useRouter } from 'vue-router'
import { changeEmail, changePassword, getAuthSessions, logoutAllDevices, revokeAuthSession } from '../api'
const router = useRouter(); const sessions = ref<{ id:number; device_name:string|null; created_at:string; last_used_at:string; expires_at:string; current:boolean }[]>([]); const password = ref(''); const newPassword = ref(''); const email = ref(''); const emailPassword = ref(''); const message = ref(''); const error = ref(''); const saving = ref(false)
async function load() { try { sessions.value = await getAuthSessions() } catch (e) { error.value = e instanceof Error ? e.message : '安全信息加载失败' } }
async function updatePassword() { saving.value = true; message.value = ''; error.value = ''; try { await changePassword(password.value, newPassword.value); message.value = '密码已修改，所有设备已退出，请重新登录'; password.value = ''; newPassword.value = ''; window.dispatchEvent(new Event('auth-signed-out')); setTimeout(() => router.push('/'), 700) } catch (e) { error.value = e instanceof Error ? e.message : '密码修改失败' } finally { saving.value = false } }
async function updateEmail() { saving.value = true; message.value = ''; error.value = ''; try { await changeEmail(emailPassword.value, email.value); message.value = '邮箱已更新'; emailPassword.value = '' } catch (e) { error.value = e instanceof Error ? e.message : '邮箱修改失败' } finally { saving.value = false } }
async function logoutDevice(item: { id: number; current: boolean }) { if (item.current) return; try { await revokeAuthSession(item.id); sessions.value = sessions.value.filter((session) => session.id !== item.id); message.value = '已退出该设备'; error.value = '' } catch (e) { error.value = e instanceof Error ? e.message : '退出设备失败' } }
async function logoutAll() { await logoutAllDevices(); window.dispatchEvent(new Event('auth-signed-out')); await router.push('/') }
onMounted(load)
</script>
<template><div class="page-container security-page"><RouterLink class="back-link" to="/me"><ArrowLeft :size="16" />返回用户主页</RouterLink><div class="page-title-row"><div><span class="eyebrow">ACCOUNT SECURITY</span><h1>账号安全</h1><p>修改密码、邮箱并管理登录设备。</p></div><ShieldCheck :size="28" class="accent-icon" /></div><p v-if="message" class="success-banner">{{ message }}</p><p v-if="error" class="form-error">{{ error }}</p><section class="security-section"><div class="section-heading"><div><span class="eyebrow">PASSWORD</span><h2>修改密码</h2></div><KeyRound :size="19" /></div><form @submit.prevent="updatePassword"><label>当前密码<input v-model="password" type="password" autocomplete="current-password" required /></label><label>新密码<input v-model="newPassword" type="password" autocomplete="new-password" minlength="6" required /></label><button class="primary-button" :disabled="saving">保存新密码</button></form></section><section class="security-section"><div class="section-heading"><div><span class="eyebrow">EMAIL</span><h2>修改邮箱</h2></div><UserRound :size="19" /></div><form @submit.prevent="updateEmail"><label>新邮箱<input v-model="email" type="email" autocomplete="email" required /></label><label>当前密码<input v-model="emailPassword" type="password" autocomplete="current-password" required /></label><button class="secondary-button" :disabled="saving">更新邮箱</button></form><small class="muted-note">邮箱验证邮件需要配置邮件服务后启用。</small></section><section class="security-section"><div class="section-heading"><div><span class="eyebrow">DEVICES</span><h2>登录设备</h2></div><Monitor :size="19" /></div><div v-for="item in sessions" :key="item.id" class="device-row"><span><Monitor :size="17" /><strong>{{ item.device_name || '未知设备' }}</strong></span><div class="device-actions"><small>{{ item.current ? '当前设备' : '已登录设备' }} · {{ new Date(item.last_used_at).toLocaleString() }}</small><button v-if="!item.current" type="button" @click="logoutDevice(item)">退出此设备</button></div></div><button class="danger-button-wide" :disabled="!sessions.length" @click="logoutAll">退出全部设备</button></section></div></template>
<style scoped>.security-page{max-width:800px}.back-link{display:inline-flex;align-items:center;gap:6px;color:var(--primary);font-size:13px;margin-bottom:26px}.accent-icon{color:var(--accent);margin-top:20px}.security-section{padding-top:34px;margin-top:30px;border-top:1px solid var(--border)}.security-section form{max-width:460px;display:grid;gap:14px}.security-section label{display:grid;gap:7px;color:var(--secondary);font-size:12px}.security-section input{padding:10px;border:1px solid var(--border);background:var(--surface);outline:0}.device-row{display:flex;justify-content:space-between;align-items:center;gap:12px;padding:14px 0;border-bottom:1px solid var(--border)}.device-row span{display:flex;align-items:center;gap:8px}.device-row small,.muted-note{color:var(--secondary);font-size:11px}.device-actions{display:flex;align-items:center;gap:10px}.device-actions button{padding:5px 9px;border:1px solid var(--border);background:transparent;color:var(--danger);font-size:11px}.danger-button-wide{margin-top:18px;padding:10px 14px;border:1px solid var(--danger);background:transparent;color:var(--danger)}.success-banner{padding:11px;background:var(--primary-soft);color:var(--primary);font-size:13px}.form-error{color:var(--danger);font-size:13px}@media(max-width:600px){.device-row{align-items:flex-start;flex-direction:column}.device-actions{width:100%;justify-content:space-between}}
</style>
