<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { CalendarDays, Clock3, MapPin, Share2 } from 'lucide-vue-next'
import { useRoute } from 'vue-router'
import { api, type Itinerary } from '../api'
const route = useRoute(); const itinerary = ref<Itinerary | null>(null); const error = ref(''); const loading = ref(true)
onMounted(async () => { try { itinerary.value = await api<Itinerary>(`/shares/${route.params.token}`) } catch (e) { error.value = e instanceof Error ? e.message : '分享链接已失效' } finally { loading.value = false } })
</script>
<template><div class="page-container shared-page"><div v-if="loading" class="loading-state">正在打开分享行程...</div><div v-else-if="error" class="empty-state"><Share2 :size="28" /><h2>{{ error }}</h2></div><template v-else-if="itinerary"><div class="shared-label"><Share2 :size="16" />行旅 · 只读分享</div><header class="page-title-row"><div><span class="eyebrow">{{ itinerary.city_name }} · {{ itinerary.days }} DAYS</span><h1>{{ itinerary.title }}</h1><p>这是一份只读行程分享，不包含分享者的账号信息。</p></div></header><div class="shared-facts"><span><CalendarDays :size="15" />{{ itinerary.days }} 天</span><span>预算 ¥{{ itinerary.budget_total }}</span></div><section class="timeline"><div v-for="day in itinerary.itinerary_days" :key="day.day_number" class="day-block"><div class="day-label"><b>DAY {{ String(day.day_number).padStart(2, '0') }}</b><span>{{ day.title }}</span></div><div v-for="stop in day.stops" :key="stop.id" class="stop-row"><div class="stop-time"><Clock3 :size="14" />{{ stop.start_time }}<small>{{ stop.end_time }}</small></div><div class="stop-dot"></div><div class="stop-content"><h3>{{ stop.name }}</h3><p>{{ stop.note }}</p></div></div><p v-if="!day.stops.length" class="muted-text">当天暂未安排景点。</p></div></section><footer class="shared-footer"><MapPin :size="15" />由行旅旅游规划助手生成</footer></template></div></template>
<style scoped>.shared-page{max-width:800px}.shared-label{display:flex;align-items:center;gap:7px;color:var(--primary);font-size:12px;margin-bottom:24px}.shared-facts{display:flex;gap:20px;padding:18px 0;border-bottom:1px solid var(--border);color:var(--secondary);font-size:12px}.shared-facts span{display:flex;align-items:center;gap:5px}.timeline{margin-top:34px}.shared-footer{display:flex;align-items:center;gap:6px;padding-top:24px;border-top:1px solid var(--border);color:var(--secondary);font-size:11px}</style>
