<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { BookOpen, Check, Clock3, Heart, Save, Settings, Trash2, UserRound } from 'lucide-vue-next'
import { api, clearRecentViews, getFavorites, getRecentViews, getUserProfile, setFavorite, updateUserProfile, type FavoriteItem, type RecentView, type UserProfile } from '../api'
const profile = ref<UserProfile>({ display_name: null, preferences: [], avoid_places: [] }); const favorites = ref<FavoriteItem[]>([]); const recent = ref<RecentView[]>([]); const loading = ref(true); const saving = ref(false); const message = ref(''); const error = ref('')
const preferenceText = ref(''); const avoidText = ref('')
async function load() { try { [profile.value, favorites.value, recent.value] = await Promise.all([getUserProfile(), getFavorites(), getRecentViews()]); preferenceText.value = profile.value.preferences.join('、'); avoidText.value = profile.value.avoid_places.join('、') } catch (e) { error.value = e instanceof Error ? e.message : '用户主页加载失败' } finally { loading.value = false } }
async function saveProfile() { saving.value = true; message.value = ''; try { profile.value = await updateUserProfile({ display_name: profile.value.display_name, preferences: preferenceText.value.split(/[、,，]/).map((item) => item.trim()).filter(Boolean), avoid_places: avoidText.value.split(/[、,，]/).map((item) => item.trim()).filter(Boolean) }); preferenceText.value = profile.value.preferences.join('、'); avoidText.value = profile.value.avoid_places.join('、'); message.value = '资料已保存' } catch (e) { error.value = e instanceof Error ? e.message : '保存失败' } finally { saving.value = false } }
async function removeFavorite(item: FavoriteItem) { await setFavorite(item.target_type, item.target_id, false); favorites.value = favorites.value.filter((entry) => !(entry.target_type === item.target_type && entry.target_id === item.target_id)) }
async function clearHistory() { await clearRecentViews(); recent.value = [] }
function link(item: FavoriteItem | RecentView) { return item.target_type === 'city' ? `/cities/${item.name === '北京' ? 'beijing' : item.name === '上海' ? 'shanghai' : 'chengdu'}` : item.target_type === 'itinerary' ? `/itineraries/${item.target_id}` : `/attractions/${item.target_id}` }
onMounted(load)
</script>
<template><div class="page-container user-home"><div v-if="loading" class="loading-state">正在加载用户主页...</div><div v-else-if="error" class="empty-state"><UserRound :size="28" /><h2>{{ error }}</h2></div><template v-else><div class="page-title-row"><div><span class="eyebrow">YOUR SPACE</span><h1>{{ profile.display_name || '我的主页' }}</h1><p>管理你的旅行偏好、收藏和浏览记录。</p></div><RouterLink class="secondary-button" to="/me/settings/security"><Settings :size="16" />账号安全</RouterLink></div><section class="user-grid"><div class="profile-section"><div class="section-heading"><div><span class="eyebrow">PREFERENCES</span><h2>旅行偏好</h2></div><UserRound :size="20" class="muted-icon" /></div><label>我的称呼<input v-model="profile.display_name" maxlength="50" placeholder="例如：大鹏" /></label><label>喜欢的内容<input v-model="preferenceText" placeholder="例如：拍照、美食、历史文化" /></label><label>不想去的地方<input v-model="avoidText" placeholder="例如：过于拥挤的景点" /></label><button class="primary-button" :disabled="saving" @click="saveProfile"><Save :size="16" />{{ saving ? '保存中...' : '保存偏好' }}</button><span v-if="message" class="success-text"><Check :size="15" />{{ message }}</span></div><div class="profile-section"><div class="section-heading"><div><span class="eyebrow">MY FAVORITES</span><h2>我的收藏</h2></div><Heart :size="20" class="accent-icon" /></div><div v-if="!favorites.length" class="small-empty">还没有收藏内容</div><RouterLink v-for="item in favorites" :key="`${item.target_type}-${item.target_id}`" class="saved-row" :to="link(item)"><span>{{ item.target_type === 'city' ? '城市' : item.target_type === 'itinerary' ? '行程' : '景点' }}</span><strong>{{ item.name }}</strong><button class="icon-button" aria-label="取消收藏" title="取消收藏" @click.prevent="removeFavorite(item)"><Trash2 :size="15" /></button></RouterLink></div></section><section class="profile-section"><div class="section-heading"><div><span class="eyebrow">RECENT VIEWS</span><h2>最近浏览</h2></div><button class="text-button" :disabled="!recent.length" @click="clearHistory">清空</button></div><div v-if="!recent.length" class="small-empty">暂时没有浏览记录</div><RouterLink v-for="item in recent" :key="`${item.target_type}-${item.target_id}`" class="saved-row" :to="link(item)"><span><Clock3 :size="14" />{{ item.target_type === 'city' ? '城市' : '景点' }}</span><strong>{{ item.name }}</strong></RouterLink></section><section class="profile-section account-shortcut"><BookOpen :size="18" /><RouterLink to="/itineraries">查看历史行程</RouterLink></section></template></div></template>
<style scoped>.user-home{max-width:1000px}.user-grid{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:48px;margin-top:48px}.profile-section{padding-top:24px;border-top:1px solid var(--color-border-soft)}.profile-section label{display:grid;gap:7px;margin-bottom:16px;color:var(--color-muted);font-size:13px}.profile-section input{min-height:48px;padding:12px;border:1px solid var(--color-border);border-radius:var(--radius-control);background:var(--color-surface);color:var(--color-ink);outline:0}.profile-section input:focus{border-color:var(--color-ink)}.success-text{display:inline-flex;align-items:center;gap:5px;margin-left:12px;color:var(--color-muted);font-size:13px}.saved-row{min-height:56px;display:grid;grid-template-columns:78px minmax(0,1fr) auto;align-items:center;gap:10px;border-bottom:1px solid var(--color-border-soft);font-size:14px}.saved-row:hover{background:var(--color-surface-soft)}.saved-row span{display:flex;align-items:center;gap:5px;color:var(--color-muted);font-size:13px}.saved-row strong{color:var(--color-ink);font-weight:600}.small-empty{padding:24px 0;color:var(--color-muted);font-size:14px}.account-shortcut{display:flex;align-items:center;gap:9px;margin-top:48px;padding-top:24px;border-top:1px solid var(--color-border-soft);color:var(--color-primary)}.accent-icon{color:var(--color-primary);margin-top:17px}@media(max-width:744px){.user-grid{grid-template-columns:1fr;gap:36px;margin-top:36px}}
</style>
